# Condition Handling and Recovery
#' Catch and Save Errors and Warnings
#'
#' This function provides a mechanism for handling unusual conditions such as
#' errors and warnings. This is Martin Maechler's \code{tryCatch.W.E} which catches
#' *and* saves both **errors** and **warnings**, and in the case of a warning,
#' also keeps the computed result.
#'
#' @export catch.conditions
#'
#' @param expr expression to be evaluated.
#'
#' @details
#' Conditions are represented as objects that contain information about the
#' condition that occurred, such as a message and the call in which the
#' condition occurred.
#' The function catches errors without actually running into error. It invokes
#' \code{'muffleWarning'} restart to prevent printing warning and then calls
#' \link{withCallingHandlers} and \link{tryCatch} to catch and return, after
#' the evaluation of expr, any unusual conditions such as errors and warnings.
#'
#' @return A list with components:
#' \item{value}{the result of the evaluation, a regular object or an error message.}
#' \item{warning}{warning message(s) generated by the evaluation, \code{NULL} if none.}
#'
#' @note
#' This function is from R base's demo \code{'demo(error.catching)'}.
#'
#' Copyright (C) 2010-2012 The R Core Team.
#'
#' @seealso
#' See the functions \link{tryCatch} and \link{withCallingHandlers} which
#' \code{catch.conditions} wraps.
#'
catch.conditions <- function (expr) {
  W <- NULL
  w.handler <- function(w)
  {
    W <<- w
    invokeRestart("muffleWarning")
  }
  list(value = withCallingHandlers(tryCatch(expr,
                                            error = function(e) e), warning = w.handler),
       warning = W)
}
